### ISSUE TITLE
Unable to connect to Zotero from Logseq on Windows 11

### ISSUE THREAD

**Issue by rdevriese** [benjypng/logseq-zoterolocal-plugin#11]
Completely uninstalled Zotero 6x and installed Zotero 7.0.1.
Configured Zotero according to instruction—allow access from other applications. Set Better Bibtex to sync citations after one second.
With Zotero running I launched Logseq 0.10.9. Get error message saying Unable to retrieve items from Zotero.
Repeated the whole procedure twice and rebooted after installing Zotero.
Nada. The plugin cannot access Zotero.

**Comment by 0WD0** [comment]
Same problem, and so for arch linux.
The api component might be something wrong.

**Comment by 0WD0** [comment]
The debug log from zotero

(5)(+0018649): OPTIONS /api/users/0/items HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Accept: */* Access-Control-Request-Method: HEAD Access-Control-Request-Headers: content-type,x-zotero-connector-api-version,zotero-allowed-request Origin: lsp://logseq.io User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Logseq/0.10.9 Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36 Sec-Fetch-Mode: cors Sec-Fetch-Site: cross-site Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br Accept-Language: en-US

(5)(+0000002): HTTP/1.0 200 OK X-Zotero-Version: 7.0.1 X-Zotero-Connector-API-Version: 2 Content-Length: 0 

Is there any problem?

**Comment by benjypng** [comment]
Just to double check, in your plugin settings, do you have the green checkmark, but get the issue when trying to do a search?

**Comment by rdevriese** [comment]
No, the green checkmark is not checked. The plugin settings say that a
connection cannot be made with zotero.

**Comment by benjypng** [comment]
Thanks @rdevriese.

I've made a PR to the marketplace to see if the additional plugin setting fixes the issue. Will update when it has been merged.

**Comment by benjypng** [comment]
@rdevriese Please update the plugin and try again.

**Comment by rdevriese** [comment]
The latest update resolved the connection issue. Thanks!

**Comment by noppelmax** [comment]
For me as well.
