### ISSUE TITLE
Plugin fails "connection test"

### ISSUE THREAD

**Issue by odysseus90210** [benjypng/logseq-zoterolocal-plugin#12]
Since I've installed the plugin, I'm informed that it is "unable to retrieve items from Zotero." Zotero is running. I'm running Zotero 7.0.1. I don't know how to troubleshoot this, honestly.

**Comment by imustd** [comment]
same with me. even installed better bibtex, still not working.

**Comment by imustd** [comment]
I tried installing using Load unpacked plugin, it worked. Turn on developer mode in settings to do this.

**Comment by 0WD0** [comment]
@imustd It works.

**Comment by imustd** [comment]
@odysseus90210 Are you able to insert full item? I am facing this error: "Ensure that the template property 'template-including-parent' is set to false". Can you please help?

**Comment by 0WD0** [comment]
Just create the template

**Comment by odysseus90210** [comment]
It may well be a problem with Logseq for MacOS. I’m running version 7.0.2 under MacOS 14.6.1

**Comment by odysseus90210** [comment]
Why isn't the developer commenting on this?

**Comment by benjypng** [comment]
> Why isn't the developer commenting on this?

Unfortunately it's because the developer has a full-time job. I've made a PR to the marketplace to see if the additional plugin setting fixes the issue. Will update when it has been merged.

**Comment by benjypng** [comment]
> @odysseus90210 Are you able to insert full item? I am facing this error: "Ensure that the template property 'template-including-parent' is set to false". Can you please help?

I've created a new issue for this: https://github.com/benjypng/logseq-zoterolocal-plugin/issues/13, and have some questions there. Thanks!

**Comment by benjypng** [comment]
@odysseus90210 Please update the plugin and try again.

**Comment by odysseus90210** [comment]
It's working!! Thank you so much!

**Comment by odysseus90210** [comment]
Sorry to ask this: if I insert a citation, it says "not in graph." Does there have to be a page for every reference?

**Comment by benjypng** [comment]
If you insert a citation, it doesn't count as being in graph because there is no page actually created for it.

**Comment by odysseus90210** [comment]
But creating a page first for it isn’t necessary, is it? Regardless, nothing is inserted (just @null). I’ve pored over the ReadMe and can’t tell what I’m doing wrong!

**Comment by benjypng** [comment]
Could you share your plugin settings?

**Comment by odysseus90210** [comment]
Here you go. These are the plain vanilla settings.

<img width="1101" alt="Screenshot 2024-08-22 at 6 34 18 AM" src="https://github.com/user-attachments/assets/88373a78-c316-4c0a-adb5-682de336ac8d">

On the Zotero side, do I have BetterBibTeX correctly configured?

<img width="912" alt="Screenshot 2024-08-22 at 6 35 28 AM" src="https://github.com/user-attachments/assets/37f145de-0d48-4183-9996-2d6263362c5a">
