### ISSUE TITLE
Error: "Ensure that the template property 'template-including-parent' is set to false"

### ISSUE THREAD

**Issue by benjypng** [benjypng/logseq-zoterolocal-plugin#13]
@imustd, can you screenshot the template you created using `/Insert Zotero Template`, and your plugin settings page?

**Comment by imustd** [comment]
@benjypng Oh! In the usage section, those three are the steps to adding an item. I was earlier considering them as three functionalities of your plugin. 

Can you please confirm the workflow? 
Can I add more than one item to a single journal?
I want to highlight stuff in Zotero and write notes in Logseq; is there any way to include those highlights?

**Comment by benjypng** [comment]
> Can you please confirm the workflow?

Step 1: Go to any page, e.g. [[templates]] and use the slash command `/Insert Zotero template`. If you are ok with the defaults, nothing else needs to be done.

Step 2: Go to the page where you want to insert the reference to the journal item, for example in the daily notes page. Use the slash command `/Zotero: Insert full item` and choose the item you want.

> Can I add more than one item to a single journal?

What do you mean by more than one item?

>  I want to highlight stuff in Zotero and write notes in Logseq; is there any way to include those highlights?

Yes, this is supported by the default template (above).

**Comment by imustd** [comment]
Getting this issue now: file not getting added, even after the "Completed!" popup. 
![ScreenRecording2024-08-22at06 30 09-ezgif com-video-to-gif-converter (1)](https://github.com/user-attachments/assets/b8c663d5-f10b-4bfc-8177-ddffcdfa7a14)

>  Yes, this is supported by the default template (above).

This is not working. Do I have to change the template?
<img width="703" alt="image" src="https://github.com/user-attachments/assets/bbde78f0-a365-436a-a7a3-1be53b592ffe">

**Comment by benjypng** [comment]
> Getting this issue now: file not getting added, even after the "Completed!" popup.

Could you delete the page that was created, update the Zotero plugin, and try again?

**Comment by imustd** [comment]
Thank you so much! 

Everything's working except highlights; please help with this also.

**Comment by benjypng** [comment]
What about highlight?

**Comment by imustd** [comment]
Can we see highlights from Zotero in Logseq?

**Comment by benjypng** [comment]
You have to right click on the item in Zotero and choose create note from highlights. That note can then be pulled into Logseq.
