### ISSUE TITLE
Pulling linked files and URL

### ISSUE THREAD

**Issue by 0WD0** [benjypng/logseq-zoterolocal-plugin#14]
Is it possible to pull linked files and URLs to the attechment block in logseq?

**Comment by benjypng** [comment]
Linked attachments are not supported in Zotero 7 at the moment.

**Comment by 0WD0** [comment]
OK, got it. So pulling the urls is possible?

**Comment by benjypng** [comment]
Yes. If you insert a full item you should be able to see it.

**Comment by 0WD0** [comment]
But, I can't see it...

**Comment by 0WD0** [comment]
URL was not attached and why only the asdfg note was pulled?
![image](https://github.com/user-attachments/assets/2ad137da-db85-4c21-822d-3b54fef6e88f)
![image](https://github.com/user-attachments/assets/5d60ae8f-2ded-4a3c-83b3-22749315b474)

**Comment by 0WD0** [comment]
So you mean the URL in the sidebar?

**Comment by benjypng** [comment]
I see the URL under libraryLink. Is there another URL you are referring to?

**Comment by 0WD0** [comment]
Oh, I'm referring to the url attachment

**Comment by benjypng** [comment]
I see. Will need an enhancement. Let me look into it when I have the time.

**Comment by benjypng** [comment]
Available in latest version.
