### ISSUE TITLE
Error loading items

### ISSUE THREAD

**Issue by 0WD0** [benjypng/logseq-zoterolocal-plugin#15]
At first there's no problem, after downloading better bibtex plugin and sync my zotero data this error occured.
latest version loaded from plugin market
on Windows11
the connection is ok
![image](https://github.com/user-attachments/assets/3c663757-6148-42d5-b51e-38fcc0c8a22b)

**Comment by benjypng** [comment]
Are you able to see what the console logs say?

**Comment by 0WD0** [comment]
I checked the console log.
The problem is caused by an unacessable linked file.
My fault.
