### ISSUE TITLE
Problem about refreshing logseq

### ISSUE THREAD

**Issue by 0WD0** [benjypng/logseq-zoterolocal-plugin#17]
If the "R: citekey" pages is not linked ,it will be renamed by its title (the title property) automatically after refreshing logseq.
This a normal phenomenon for logseq. Because of this, users may be confused by the inability to find pages via "R: citekey" after refreshing.

**Comment by benjypng** [comment]
I've added error messages. Please try the latest version.

**Comment by pratipo** [comment]
i just installed it and get the same results after re-indexing, which is necessary for aliases and icons to show up.
an easy solution is to replace the field "title" for something else, "itemtitle" for example.

`title:: <% title %> --> itemtitle:: <% title %>`

**Comment by benjypng** [comment]
You can actually change the template for the page properties on your own. In your Zotero template, after you do `/Zotero: Insert template`, you can change it from `title:: <% title %>` to `itemTitle: <% title %>`.
