### ISSUE TITLE
No text appears after selecting an item

### ISSUE THREAD

**Issue by noppelmax** [benjypng/logseq-zoterolocal-plugin#18]
Hey everybody,

my Zotero connection works now: I do have the green icon in the plugin settings and I can fetch items with `Zotero: Insert full item`. I then click on one of the found paper and get a popup `Completed`. But nothing happens. No text or anything appears.

Do you have any idea how to solve this? Is there a debug log somewhere?

Max

On Ubuntu 23.04. LogSeq from Snap, Zotero 7, Current plugin version.

**Comment by 0WD0** [comment]
I have same problem on Windows, but on archlinux it's fine.

**Comment by benjypng** [comment]
I've added error messages. Please try the latest version.

**Comment by krizzodil** [comment]
Hi, first, thank you so much for your plugin!
I might have the same or a similar problem with the current version of Logseq 0.10.9 and with the current version of your plugin available on the marketplace as well as with your current version 2.5.4.

After selecting an entry the messages "Inserting into graph" appear, followed by the error message "Ensure that the template property 'template-including-parent' is set to false.

I am completely new to Logseq so I don't understand much yet, but there might be a problem with the template. When I bring it up with the corresponding command it looks like this. Notice the double colons. Could this be a new bug of Logseq itself?

![image](https://github.com/user-attachments/assets/cb992d68-5523-4b04-a708-f2188036cfe0)

**Comment by benjypng** [comment]
Could you show me your plugin settings please?

**Comment by krizzodil** [comment]
> Could you show me your plugin settings please?

Sure, there you go:
![image](https://github.com/user-attachments/assets/e9365a50-bcdc-49f4-827f-10f0c52c4a51)

**Comment by benjypng** [comment]
Ah ok I see the issue. In your template, there is a space between the start of the line and the block property. It currently is:

```
Zotero Template
    template:: Zotero Template
    template-imcluding-parent:: false
```

but it should be:

```
Zotero Template
template:: Zotero Template
template-imcluding-parent:: false
```

**Comment by krizzodil** [comment]
Ah! Thank you so much! I removed those leading spaces and that did it. 
Though I don't know how those spaces came to be.

**Comment by odysseus90210** [comment]
> I've added error messages. Please try the latest version.

Thanks. Now I’m seeing an error “Citation Key Not Configured Correctly.” Your documentation only mentions setting “Automatically pin citation key after” to “1 second." How should the Citation Key be configured? It is currently set to the default, I think: auth.lower + shorttitle(3,3) + year

**Comment by noppelmax** [comment]
I also had the leading spaces. However, removing them from the template did not solve the problem in plugin version v2.6.1. I still got the error:

![image](https://github.com/user-attachments/assets/4cf9af81-092c-4168-8807-9adb2e165291)

My template looks like this: ( I changed nothing in comparison to /insert Latex Template version, except for removing the spaces.)

![image](https://github.com/user-attachments/assets/fe8e55e8-f28c-4006-beae-226a6bd0077d)

And my settings are also default. Any idea? I'm on Ubuntu 23.04.

**Comment by noppelmax** [comment]
Should be the same issue as #20, I guess.

**Comment by benjypng** [comment]
Could you try the latest release (`2.6.2`) and report back what you see? I am tempted to just remove the check but am concerned with side-effects at this point.

**Comment by noppelmax** [comment]
![image](https://github.com/user-attachments/assets/bd30a841-9834-4d82-9f8c-a5c4d12bbebf)

That is what I got now.

**Comment by benjypng** [comment]
Thanks! That's helpful. Please try `2.6.3`.
