### ISSUE TITLE
Local Library link 

### ISSUE THREAD

**Issue by krillin666** [benjypng/logseq-zoterolocal-plugin#19]
Is it possible to add a placeholder for a URI link to the Zotero item ?
Thank you for your work!

**Comment by benjypng** [comment]
Hi! It's already in.

Use the placeholder `<% libraryLink %>`, e.g. `library:: <% libraryLink %>` in your template.

**Comment by krillin666** [comment]
Thank you ! What about abstract text ?

**Comment by benjypng** [comment]
Use `<% abstractNote %>`.
