### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by panangam** [benjypng/logseq-zoterolocal-plugin#2]
After using `Launch Zotero plugin`, my screen turns white, but nothing else appears. When I press ESC, the white screen disappear. So I cannot import any entry. (I have already set up the template.)

Screenshot of the screen and the console:
![image](https://github.com/user-attachments/assets/dd515e7e-33f5-4461-b066-c87ffe19e40a)

Logseq: 0.10.9
logseq-zoterolocal-plugin: 1.0.6
Reborn OS + KDE Plasma

**Comment by panangam** [comment]
@benjypng Made a PR to address this

**Comment by benjypng** [comment]
🤔 I can't reproduce this error. Items that don't have any author or even all blank fields does show up in the table properly.

**Comment by panangam** [comment]
Weird... Let me check my Zotero version. Can you see what version of Zotero
you test with as well?

**Comment by benjypng** [comment]
I'm using `7.0.0-beta.117+794dc6bf0`.

**Comment by panangam** [comment]
I'm on `7.0.0beta.115+4c32317ba-1`. Will check tomorrow if upgrading Zotero fixes it for me (it's almost midnight here).

**Comment by benjypng** [comment]
Same (🇸🇬)! I suspect that we are almost in the same timezone.

**Comment by panangam** [comment]
Cool! 🇹🇭 here!

**Comment by panangam** [comment]
I tried upgrading Zotero and got the same behavior. I did some more debugging, and it seems when querying for all items, Zotero also return `note` sub-items, which do not have creators. E.g.:

```json
$ curl  http://localhost:23119/api/users/0/items/UFQHZBQK
{
    "key": "UFQHZBQK",
    "version": 0,
    "library": {
        "type": "user",
        "id": 0,
        "name": "My Library",
        "links": {
            "self": {
                "href": "http://localhost:23119/api/users/0",
                "type": "application/json"
            }
        }
    },
    "links": {
        "self": {
            "href": "http://localhost:23119/api/users/0/items/UFQHZBQK",
            "type": "application/json"
        },
        "up": {
            "href": "http://localhost:23119/api/users/0/items/22PZBM4N",
            "type": "application/json"
        }
    },
    "meta": {
        "numChildren": 0
    },
    "data": {
        "key": "UFQHZBQK",
        "version": 0,
        "itemType": "note",
        "parentItem": "22PZBM4N",
        "note": "Comment: Project website: https://vsitzmann.github.io/siren/ Project video: https://youtu.be/Q2fLWGBeaiI",
        "tags": [],
        "relations": {},
        "dateAdded": "2024-08-08T04:47:00Z",
        "dateModified": "2024-08-08T04:47:00Z"
    }
}
```

I think the endpoint you want to use might be `<userOrGroupPrefix>/items/top `, which only return the top level items.

**Comment by benjypng** [comment]
Could you attach the specific item here? I'll import it to Zotero on my end to try and debug.

**Comment by panangam** [comment]
> Could you attach the specific item here? I'll import it to Zotero on my end to try and debug.

Pretty sure you can reproduce this by adding a note to any of your items (right click -> "Add Note"). But here's the exported file:
[Exported Items.zip](https://github.com/user-attachments/files/16573402/Exported.Items.zip)
This should give you 3 sub-items, including a note (the thing causing my problem).
![image](https://github.com/user-attachments/assets/b91952d1-283c-415b-b0b2-d5f04201f23a)

**Comment by panangam** [comment]
In case you haven't seen this, the endpoint `/items/<id>/children` will give you all the attachment. Personally I'd prefer using this so all attachments can be included in logseq. 
https://groups.google.com/g/zotero-dev/c/yOqokmHI39Q

**Comment by benjypng** [comment]
Issue has been fixed. Please try the latest version, **and** ensure that your Zotero template reflects the attachment property as `<% attachments %>`, that is attachment**s** (plural).

**Comment by panangam** [comment]
Works great now, thank you! It seems like my note item wasn't imported though. Is that still not supported yet?

Regardless, closing this since the issue is solved.

**Comment by benjypng** [comment]
Is your note item the HTML file in your zip file?

**Comment by panangam** [comment]
No, it's the yellow thing in the screenshot I sent. It doesn't have an
"enclosure" "link" in the API response cause it's just a plain text
attached with the main item.

**Comment by benjypng** [comment]
Thanks for reporting. I've created a new issue for this.
