### ISSUE TITLE
Insert Zotero item gives an error

### ISSUE THREAD

**Issue by ashiqrniloy** [benjypng/logseq-zoterolocal-plugin#20]
Hi

Thanks so much for building the plugin. I was looking for this.

I setup the plugin and Zotero based on the instructions provided. The settings page also shows that the connection is working. However, when I try to insert a zotero item, it gives an error. Please see attached.
![Zotero-logseq error](https://github.com/user-attachments/assets/3034fb9c-9dbf-4ead-bd38-239cecaa1b10)

I am also providing the template and my settings for the plugin
![Zotero Template](https://github.com/user-attachments/assets/3961dd2a-28f2-486e-b55a-62897e75a97e)
![Settings](https://github.com/user-attachments/assets/f0756ff6-d3df-43df-9267-00ec9f138771)

Would really appreciate if you could give me an idea if I am doing something wrong here. I am using Zotero 7 and latest version of the plugin. Setup the whole thing in the last hour

**Comment by benjypng** [comment]
For the second screenshot on the template could you do it without being in edit mode? Eg press Escape then take the screenshot.

**Comment by benjypng** [comment]
This should be fixed in the latest version. Am going to close this issue for now but the original author can continue to reply to this issue (I'll look out for it) or create another issue if it still persists for them.
