### ISSUE TITLE
Adding the filled in template also when I add the link [[R: citekey]] manually. It is possible?

### ISSUE THREAD

**Issue by noppelmax** [benjypng/logseq-zoterolocal-plugin#22]
Hey,

I have written some scripts for the Zotero Plugin "Actions and Scripts" that generate plaintext links like so:
```
[[R: Noppel2023Disguising]] [[item](zotero://select/library/items/KNWTWU8Y)] [[pdf](zotero://open-pdf/library/items/NRRCFQYV)]
```

This enables me to work in Zotero and copy references into LogSeq via Drag and Drop or via Shortcuts. However the respectice page `R: Noppel2023Disguising` does not contain the template then (and if it would, the template would not be filled out). Can you estimate how much effort it would be to hook your plugin into the creation of a new page and paste the template into it if it starts with `R: `? What do you think? 

Kind regards, 
Max

**Comment by benjypng** [comment]
Sorry I'm not an advanced Zotero user so I really am not sure what you mean. What does hooking the plugin into the creation of a new page mean?

**Comment by noppelmax** [comment]
Ah sorry for my fuzzy expressions. I mean hooking plugin in LogSeq, such that whenever an empty page with a name starting with R: is opened, it is execute and fills in the Zotero Template. That way I could manually create link like `[[R: Noppel2023Disguising]]` and as soon as I click on them, the plugin would do its magic: adding the template and filling it out. As far as I understand it, you only add the template and the fill it out when the `/insert zotero full item` command is excuted, right?

**Comment by benjypng** [comment]
Ah I see what you mean. Yes, the "magic" happens only when you click on the item that you want to insert and not before that.

**Comment by noppelmax** [comment]
Hmm to me it looks different. If I run `/Zotero: Insert full item` the plugin will add `[[R: <key>]]`. If I click on that link then, I get to the filled out page, according to the template. However, if I add `[[R: <key>]]` manually, e.g., by typing, for a new citekey that is not in logseq yet, and if I then click that one, I got to an empty page. Does the plugin store a list of created page internally or is it just triggered by `R: `?

**Comment by benjypng** [comment]
Here is what happens when you run '/Zotero: Insert full item' and select the item you want to add:

1. Creates the page with the title format defined in the plugin settings
2. Populates the page according to the template
3. Creates a reference to the page created in Step 1, depending on where you trigger the slash command

Which is exactly what you described. There is no 'hook' in place actually.

**Comment by noppelmax** [comment]
Hey,

okay. Thanks for the clarification. I will try to find out if it is even possible to do it the way I desire, and come back here then.

Max
