### ISSUE TITLE
Feature Request: respect in-use theme

### ISSUE THREAD

**Issue by panangam** [benjypng/logseq-zoterolocal-plugin#4]
By using CSS variable defined by Logseq, e.g. `var(--ls-primary-background-color)`, the plugin can have an appearance that matches the theme in use, like night mode. There should be enough theme-dependent variables to style everything.

**Comment by panangam** [comment]
@benjypng I'd be happy to make a PR for this. Wanted to get your opinion first.

**Comment by benjypng** [comment]
Apologies, I am not very keen to do it at this point as it introduces a lot of variability and potentially more user issues when it doesn't appear correctly in their own environment, especially since even Logseq's CSS can be overridden.

**Comment by panangam** [comment]
> Apologies, I am not very keen to do it at this point as it introduces a lot of variability and potentially more user issues when it doesn't appear correctly in their own environment, especially since even Logseq's CSS can be overridden.

Oh, interesting. I don't have work experience in frontend dev so I assume you know more than me here. Would you be open to a PR of an option to do this with a tick box in settings that defaults to false?

**Comment by benjypng** [comment]
I think the experience is specific to plugin users. Logseq has a very wide variance in both user experience, devices and environments, and in the past, changes like this brought on issues that require a lot of time to debug. 

In any case I will take note of this and perhaps revisit this again when there are multiple requests for it!

Thank you again for offering!
