### ISSUE TITLE
Notes not imported

### ISSUE THREAD

**Issue by benjypng** [benjypng/logseq-zoterolocal-plugin#5]
_Originally posted by @panangam in https://github.com/benjypng/logseq-zoterolocal-plugin/issues/2#issuecomment-2283199241_

@panangam Please try the latest version. 

You have to update your template with the placeholder `<% notes %>`. Suggest to add it as a block instead of a page property because notes can sometimes be long and unpredictable.

**Comment by panangam** [comment]
Happy to report that this worked perfectly for me!

**Comment by panangam** [comment]
@benjypng It worked! I got the note in. However, if I have 2 notes attached to an item, only one of them seem to be imported
![image](https://github.com/user-attachments/assets/eb043cbe-2e55-4587-bea4-064535304f20)
![image](https://github.com/user-attachments/assets/34649a11-55a7-4722-a590-a1f2bb1ae215)

**Comment by benjypng** [comment]
Should be fixed in v2.

Do note that the UI has changed. Had to change the entire approach to support large databases (had a user with more than 7000 items).

Trigger the plugin using `/Zotero: Insert full item`

**Comment by panangam** [comment]
Yep, works perfectly now! And I was just about to request inserting attachments as separate blocks too. Love it 👍❤️.

**Comment by benjypng** [comment]
Great!

**Comment by Sophiamer2002** [comment]
@panangam Your template looks really nice. Would you like to share your template? Thanks!
